const types = {
  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNIN: 'SIGNIN',
  SIGNUP_FAILED: 'SIGNUP_FAILED',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILED: 'SIGNIN_FAILED',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
  SET_CURRENT_USER_FAILED: 'SET_CURRENT_USER_FAILED',
  LOGOUT_USER: 'LOGOUT_USER',
};

export default types;
