// export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
// export const SIGNUP_FAILED = 'SIGNUP_FAILED';
// export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
// export const SIGNIN_FAILED = 'SIGNIN_FAILED';
// export const SET_CURRENT_USER = 'SET_CURRENT_USER';
// export const LOGOUT_USER = 'LOGOUT_USER';
const types = {
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILED: 'SIGNUP_FAILED',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILED: 'SIGNIN_FAILED',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  LOGOUT_USER: 'LOGOUT_USER',
};

export default types;
