const types = {
  CREATE_NEW_BOARD: 'CREATE_NEW_BOARD',
  CREATE_NEW_BOARD_SUCCESS: 'CREATE_NEW_BOARD_SUCCESS',
  CREATE_BOARD_FAILED: 'CREATE_BOARD_FAILED',
  GET_USER_BOARDS: 'GET_USER_BOARDS',
  DELETE_BOARD: 'DELETE_BOARD',
  DELETE_BOARD_SUCCESS: 'DELETE_BOARD_SUCCESS',
  DELETE_BOARD_FAILED: 'DELETE_BOARD_FAILED',
}

export default types;
