const types = {
  CREATE_CARD: 'CREATE_CARD',
  CREATE_CARD_SUCCESS: 'CREATE_CARD_SUCCESS',
  CREATE_CARD_FAILED: 'CREATE_CARD_FAILED',
  GET_CARDS: 'GET_CARDS',
  GET_CARDS_SUCCESS: 'GET_CARDS_SUCCESS',
  GET_CARDS_FAILED: 'GET_CARDS_FAILED',
  DELETE_CARD: 'DELETE_CARD',
  DELETE_CARD_SUCCESS: 'DELETE_CARD_SUCCESS',
  DELETE_CARD_FAILED: 'DELETE_CARD_FAILED',
  UPDATE_CARD: 'UPDATE_CARD',
  UPDATE_CARD_SUCCESS: 'UPDATE_CARD_SUCCESS',
  UPDATE_CARD_FAILED: 'UPDATE_CARD_FAILED',
};

export default types;
